<?xml version="1.0"?>
<robot name="firefighter_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Robot Constants -->
    <xacro:property name="base_width" value="0.45" />
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_height" value="0.15" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_width" value="0.08" />
    <xacro:property name="wheel_separation_width" value="0.5" />
    <xacro:property name="wheel_separation_length" value="0.45" />
    <xacro:property name="launcher_base_height" value="0.15" />
    <xacro:property name="launcher_base_size" value="0.3" />
    <xacro:property name="launcher_height" value="0.25" />
    <xacro:property name="launcher_radius" value="0.08" />

    <!-- New magazine properties -->
    <xacro:property name="magazine_width" value="0.08" />
    <xacro:property name="magazine_length" value="0.08" />
    <xacro:property name="magazine_height" value="0.3" />
    <xacro:property name="magazine_wall_thickness" value="0.005" />
    <xacro:property name="door_thickness" value="0.005" />
    <xacro:property name="ball_radius" value="0.03" />
    <!-- Removed redefining pi as it's already defined in ROS xacro -->

    <!-- Materials -->
    <material name="red">
        <color rgba="1.0 0.0 0.0 1.0" />
    </material>
    <material name="black">
        <color rgba="0.1 0.1 0.1 1.0" />
    </material>
    <material name="silver">
        <color rgba="0.7 0.7 0.7 1.0" />
    </material>
    <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0" />
    </material>
    <material name="green">
        <color rgba="0.0 0.8 0.0 1.0" />
    </material>
    <material name="orange">
        <color rgba="1.0 0.5 0.0 1.0" />
    </material>

    <!-- Robot Base -->
    <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <mass value="10.0" />
            <inertia ixx="0.22" ixy="0.0" ixz="0.0" iyy="0.45" iyz="0.0" izz="0.65" />
        </inertial>
    </link>

    <!-- Wheels -->
    <xacro:macro name="wheel_link" params="name x y">
        <link name="${name}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <mass value="1.0" />
                <inertia ixx="0.0045" ixy="0.0" ixz="0.0" iyy="0.0045" iyz="0.0" izz="0.0078" />
            </inertial>
        </link>

        <!-- Inside the wheel_link macro -->
        <joint name="${name}_wheel_joint" type="continuous">
            <parent link="base_link" />
            <child link="${name}_wheel" />
            <!-- Change z from 0 to -wheel_radius to lower wheels -->
            <origin xyz="${x} ${y} -${wheel_radius}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>

    <!-- Create 4 wheels -->
    <xacro:wheel_link name="front_left" x="${wheel_separation_length/2}"
        y="${wheel_separation_width/2}" />
    <xacro:wheel_link name="front_right" x="${wheel_separation_length/2}"
        y="-${wheel_separation_width/2}" />
    <xacro:wheel_link name="rear_left" x="-${wheel_separation_length/2}"
        y="${wheel_separation_width/2}" />
    <xacro:wheel_link name="rear_right" x="-${wheel_separation_length/2}"
        y="-${wheel_separation_width/2}" />

    <!-- New Ball Magazine (Hollow Rectangular Tube) -->
    <link name="ball_magazine">
        <visual>
            <geometry>
                <!-- For the visual, you would ideally use a mesh file from Blender -->
                <!-- placeholder using boxes to create a hollow tube -->
                <mesh filename="file://$(find rviz_simulation)/meshes/visual/ball_storage.st"
                    scale="1 1 1" />
                <!-- Fallback if mesh not available -->
                <!--
                <box size="${magazine_length} ${magazine_width} ${magazine_height}" />
                -->
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <geometry>
                <box size="${magazine_length} ${magazine_width} ${magazine_height}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="2.0" />
            <inertia ixx="0.03" ixy="0.0" ixz="0.0" iyy="0.03" iyz="0.0" izz="0.01" />
        </inertial>
    </link>

    <joint name="magazine_joint" type="fixed">
        <parent link="base_link" />
        <child link="ball_magazine" />
        <origin xyz="0 0 ${base_height}" rpy="0 0 0" />
    </joint>

    <!-- Magazine Door (Sliding Upward) -->
    <link name="magazine_door">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box
                    size="${magazine_length-magazine_wall_thickness*2} ${magazine_width-magazine_wall_thickness*2} ${door_thickness}" />
            </geometry>
            <material name="green" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box
                    size="${magazine_length-magazine_wall_thickness*2} ${magazine_width-magazine_wall_thickness*2} ${door_thickness}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1" />
            <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00002" />
        </inertial>
    </link>

    <joint name="magazine_door_joint" type="prismatic">
        <parent link="ball_magazine" />
        <child link="magazine_door" />
        <!-- Position at the bottom of the magazine -->
        <origin xyz="0 0 -${magazine_height/2 + door_thickness/2}" rpy="0 0 0" />
        <axis xyz="0 0 1" /> <!-- Door slides upward -->
        <limit lower="0" upper="0.07" effort="10" velocity="0.5" /> <!-- How far the door can slide
        up -->
    </joint>

    <!-- Ball Launcher Base -->
    <link name="launcher_base">
        <visual>
            <origin xyz="0 0 ${launcher_base_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${launcher_base_size} ${launcher_base_size} ${launcher_base_height}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0 0 ${launcher_base_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${launcher_base_size} ${launcher_base_size} ${launcher_base_height}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${launcher_base_height/2}" rpy="0 0 0" />
            <mass value="2.0" />
            <inertia ixx="0.03" ixy="0.0" ixz="0.0" iyy="0.03" iyz="0.0" izz="0.04" />
        </inertial>
    </link>

    <joint name="launcher_base_joint" type="fixed">
        <parent link="ball_magazine" />
        <child link="launcher_base" />
        <origin xyz="0 0 -${magazine_height/2 + launcher_base_height/2}" rpy="0 0 0" />
    </joint>

    <!-- Launcher Turret (can rotate 360 degrees) -->
    <link name="launcher_turret">
        <visual>
            <origin xyz="0 0 ${launcher_height/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${launcher_radius}" length="${launcher_height}" />
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <origin xyz="0 0 ${launcher_height/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${launcher_radius}" length="${launcher_height}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${launcher_height/2}" rpy="0 0 0" />
            <mass value="1.5" />
            <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.01" />
        </inertial>
    </link>

    <joint name="launcher_turret_joint" type="continuous">
        <parent link="launcher_base" />
        <child link="launcher_turret" />
        <origin xyz="0 0 ${launcher_base_height}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="100" velocity="1.0" />
    </joint>

    <!-- Launcher Barrel (can tilt for aiming) -->
    <link name="launcher_barrel">
        <visual>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${launcher_radius/2}" length="0.2" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${launcher_radius/2}" length="0.2" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
            <mass value="0.5" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.0005" />
        </inertial>
    </link>

    <joint name="launcher_barrel_joint" type="revolute">
        <parent link="launcher_turret" />
        <child link="launcher_barrel" />
        <origin xyz="0 0 ${launcher_height}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="-0.5" upper="0.5" effort="100" velocity="1.0" />
    </joint>

    <!-- Ball Feeder Mechanism -->
    <link name="ball_feeder">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.1 0.06 0.04" />
            </geometry>
            <material name="green" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.1 0.06 0.04" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.3" />
            <inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.0002" />
        </inertial>
    </link>

    <joint name="ball_feeder_joint" type="prismatic">
        <parent link="launcher_barrel" />
        <child link="ball_feeder" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="0" upper="0.05" effort="50" velocity="0.5" />
    </joint>

    <!-- Ball Visualization (for demonstration) -->
    <link name="ball">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="${ball_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="${ball_radius}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.1" />
            <inertia ixx="0.00004" ixy="0" ixz="0" iyy="0.00004" iyz="0" izz="0.00004" />
        </inertial>
    </link>

    <joint name="ball_joint" type="fixed">
        <parent link="launcher_barrel" />
        <child link="ball" />
        <origin xyz="0 0 0.2" rpy="0 0 0" />
    </joint>

    <!-- LiDAR Sensor (repositioned for better coverage) -->
    <link name="lidar_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.05" length="0.05" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.05" length="0.05" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.2" />
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
        </inertial>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="launcher_base" />
        <child link="lidar_link" />
        <origin xyz="0 0 ${launcher_base_height + 0.025}" rpy="0 0 0" />
    </joint>

    <!-- Thermal Camera (separated from barrel for stability) -->
    <link name="thermal_camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.05 0.05 0.05" />
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.05 0.05 0.05" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1" />
            <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001" />
        </inertial>
    </link>

    <joint name="thermal_camera_joint" type="fixed">
        <parent link="launcher_turret" />
        <child link="thermal_camera_link" />
        <origin xyz="0.08 0 ${launcher_height - 0.05}" rpy="0 0 0" />
    </joint>

    <!-- IR Sensor Array (in front of the robot base) -->
    <link name="ir_array_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.1 0.03 0.01" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.1 0.03 0.01" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.05" />
            <inertia ixx="0.000005" ixy="0" ixz="0" iyy="0.000005" iyz="0" izz="0.000005" />
        </inertial>
    </link>

    <joint name="ir_array_joint" type="fixed">
        <parent link="base_link" />
        <child link="ir_array_link" />
        <origin xyz="${base_length/2-0.02} 0 ${base_height - 0.01}" rpy="0 0 0" />
    </joint>

    <!-- Left IR Sensor -->
    <link name="ir_left_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.01 0.01" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.01 0.01" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01" />
            <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001" />
        </inertial>
    </link>

    <joint name="ir_left_joint" type="fixed">
        <parent link="base_link" />
        <child link="ir_left_link" />
        <origin xyz="0 ${base_width/2} ${base_height - 0.01}" rpy="0 0 ${pi/2}" />
    </joint>

    <!-- Right IR Sensor -->
    <link name="ir_right_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.01 0.01" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.01 0.01" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01" />
            <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001" />
        </inertial>
    </link>

    <joint name="ir_right_joint" type="fixed">
        <parent link="base_link" />
        <child link="ir_right_link" />
        <origin xyz="0 -${base_width/2} ${base_height - 0.01}" rpy="0 0 -${pi/2}" />
    </joint>

    <!-- IMU Sensor -->
    <link name="imu_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.02 0.02 0.02" />
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.02 0.02 0.02" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01" />
            <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001" />
        </inertial>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="0 0 ${base_height}" rpy="0 0 0" />
    </joint>

</robot>